### ISSUE TITLE
supply cap

### ISSUE THREAD

**Issue by viown** [JushBJJ/JushCoin#1]
make the supply cap something like 1m, and pre-mine all jushcoins, that way you can hand them out yourself.
give me 500k pls

**Comment by JushBJJ** [comment]
Once I start working on JushCoin transactions.

**Comment by JushBJJ** [comment]
> make the supply cap something like 1m, and pre-mine all jushcoins, that way you can hand them out yourself.
> give me 500k pls


I'm gonna generate your address in a few hours.

**Comment by viown** [comment]
This transaction must be highly secure and confidential.
Send me the public and private key via toaster.

**Comment by JushBJJ** [comment]
Your address is:
1ac0250545f2e3f53d816baf1450dfbc79dde4ff0209762ba6298f1f2604e218

You will get public and private key when I push the first actual commit.
